### ISSUE TITLE
Course Page

### ISSUE THREAD

**Issue by Cheyans** [ripples/lv-client#14]
Description
Start/End date (based on semester)
Professor
Etc.

**Comment by marymoser** [comment]
Concept for Course Page: Pretty similar to Feed, but with single wrapper/card dedicated to single course. Collapseable sections may not be necessary (except perhaps for lectures, which could be a long list)
![wf_course_view_1](https://cloud.githubusercontent.com/assets/11800862/16939893/a4113140-4d53-11e6-8dee-1b88ae11a83f.png)

More design concepts to come! (Maybe? Hopefully?)
