### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by Cheyans** [ripples/lv-client#5]

**Comment by marymoser** [comment]
Didn't make any formal wireframes for this yet, but I can if desired. (See my notes on Login Page issue.)

**Comment by marymoser** [comment]
A few alternatives to the Landing Page scheme. I can also try working out a more traditional homepage using a background/body wrapper that resembles the background/cards in the other designs.
![wf_home_view_1](https://cloud.githubusercontent.com/assets/11800862/16939794/d5f18e22-4d52-11e6-9159-50abea3d9f7f.png)
![wf_home_view_2](https://cloud.githubusercontent.com/assets/11800862/16939795/d5f6ca36-4d52-11e6-8d7e-06e9c054a194.png)
Alternatively, logged-out users could be taken directly to login, and once logged in, users are directed immediately to the Feed page (perhaps with a default list selection, e.g. All Courses, All Courses of Current Semester)
