### ISSUE TITLE
Admin page

### ISSUE THREAD

**Issue by timdrichards** [ripples/lv-client#8]
We will also need an admin page that allows an administrator to add/remove instructors and manage other admin like stuff.

**Comment by marymoser** [comment]
Concept 1 for Admin Page (making a few tweaks to a second design which will be uploaded soon).

I should note that, when viewing users, more search/filtering options will probably need to be in place, given the large number of instructors/students in the school.

Instructor Admin page can probably follow a similar layout to regular admin, just with appropriate controls/links. ![wf_admin_view_1-20](https://cloud.githubusercontent.com/assets/11800862/17140655/3a13216c-5317-11e6-9bbb-ee3837fe6492.png)
