### ISSUE TITLE
Instructor admin page

### ISSUE THREAD

**Issue by timdrichards** [ripples/lv-client#9]
We need an instructor admin page to view roster, add/remove students, set permissions for TAs, etc.

**Comment by marymoser** [comment]
Gotcha. If desired I can make some wireframes for this as well. Obviously (with this and the other pages) the overall design/layout is partially dependent on what consistent elements we want across most/all of the views (e.g. headers, footers, and maybe sidebars), so I'll try to keep it slightly open-ended on those aspects. But as far as anything in the body I can try brainstorming some ways to organize the functionality.
